name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        php: ['7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5']

    name: PHP ${{ matrix.php }} tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: ${{ matrix.php == '8.0' && 'xdebug' || 'none' }}

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Execute tests
        if: ${{ matrix.php != '8.0' }}
        run: ./vendor/bin/phpunit --testdox

      - name: Execute tests with coverage (Clover)
        if: ${{ matrix.php == '8.0' }}
        env:
          XDEBUG_MODE: coverage
        run: ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml --testdox

      - name: Upload coverage to Qlty
        if: ${{ matrix.php == '8.0' }}
        uses: qltysh/qlty-action/coverage@v2
        with:
          oidc: true
          files: build/logs/clover.xml

      - name: Upload the reports to coveralls.io
        if: ${{ matrix.php == '8.0' }}
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: build/logs/clover.xml
          format: clover
          flag-name: Unit
          allow-empty: false